version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
artifacts:
  files:
    - .\bin\Debug\netcoreapp3.0\*
  type: "S3",
  location: "pantusingh",
  packaging: "ZIP",
  name: "letscodeartifact.zip"