version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.0
  pre_build:
    commands:
      - printenv
    finally:
      - echo "finally this command runs"
  build:
    commands:
      - dotnet restore
      - dotnet build
artifacts:
  files:
    - ./bin/Debug/netcoreapp3.0/*
